name: .NET Release (master tagged with version tag, for example v0.1.2)

on:
  push:
    tags:
      - '*'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish
      run: dotnet publish --runtime win-x64 --configuration Release -p:PublishSingleFile=true -p:PublishTrimmed=true --self-contained true
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        name: binaries
        path: sales-lookup/bin/**/publish/*
    - name: Create Release
      uses: ncipollo/release-action@v1.8.10
      with:        
        # An optional flag which indicates if artifact read or upload errors should fail the build.
        artifactErrorsFailBuild: true # optional, default is 
        # An optional set of paths representing artifacts to upload to the release. This may be a single path or a comma delimited list of paths (or globs)
        artifacts: sales-lookup/bin/**/publish/*.exe
